on:
  schedule:
    - cron: '8 * * * *'

jobs:
  scheduled_health_check:
    runs-on: ubuntu-latest
    steps:
      - name: url health check
        uses: Jtalk/url-health-check-action@v3.1
        with:
          url: https://fullstack-11-final.fly.dev/health
          max-attempts: 3
          retry-delay: 5s
